# Generated by Django 5.2.8 on 2025-11-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_request_received', models.DateTimeField()),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('lab_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_age', models.IntegerField()),
                ('patient_bed_number', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_birth_date', models.DateField()),
                ('patient_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_other_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ppatient_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_surname', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_ward', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_type', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('open_mrs_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='labapp.labrequest')),
            ],
        ),
    ]
